### PR TITLE
Add SymbologyEncoding / SLD 1.1 Support

### PR DESCRIPTION
**Pull request by weskamm**
This adds support for writing SLD v1.1 / SymbologyEncoding.
The parser got two new configuration properties to indicate that it should write SLD 1.1 and which unit shall be used for symbolizers.

@geostyler/devs please review

### CODE REVIEW

**Comment by KaiVolland** [comment]
Is this symbology encoding supported in 1.0.0 too?

**Comment by weskamm** [comment]
officially - no

**Review by hwbllmnn — APPROVED** [review]

**Review by KaiVolland — CHANGES_REQUESTED** [review]
We should split the parser like discussed in the issue #288.

**Comment by KaiVolland** [comment]
IMHO we should introduce a `sldVersion` property (replaces `useSymbologyEncoding`?) which can be set to `1.0.0` or `1.1.0` (default 1.0.0).

Best practice would be to have two new files including specific handling or overrides for `1.0.0` and `1.1.0`. We should then have an interface and so on…
But as mentioned by @weskamm and @hwbllmnn the changes introduced by `1.1.0` are quite small.

So for now introducing just one seperate file containing the SE related changes should be sufficent.

**Comment by weskamm** [comment]
done, please review once more

**Review by KaiVolland — APPROVED** [review]
Nice.

**Comment by weskamm** [comment]
Thanks for reviews!

**Pull request merged**
